[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "gnn-materials"
version = "0.1.0"
description = "GNN prediction of formation energies and band gaps from 3D crystal structures"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "torch",
    "jarvis-tools",
]

[tool.setuptools.packages.find]
where = ["src"]